<?php

return [
    'list' => [
        "Bank BCA",
        "Bank Mandiri",
        "Bank BNI",
        "Bank BRI",
        "Bank BTN",
        "Bank CIMB Niaga",
        "Bank Danamon",
        "Bank Permata",
        "Bank Maybank Indonesia",
        "Bank Panin",
        "Bank OCBC NISP",
        "Bank UOB Indonesia",
        "Bank HSBC Indonesia",
        "Bank DBS Indonesia",
        "Standard Chartered Bank",
        "Citibank",
        "Jago",
        "SeaBank",
        "BCA Digital (Blu)",
        "Bank Syariah Indonesia (BSI)",
        "Bank Muamalat",
        "BTPN",
        "Bank Sinarmas",
        "Bank Mega",
        "Bank Bukopin",
        "Bank Jabar Banten (BJB)",
        "Bank DKI",
        "Bank Jateng",
        "Bank Jatim",
        "Bank Nagari",
        "Bank Sumut",
        "Bank Riau Kepri",
        "Bank Sumsel Babel",
        "Bank Lampung",
        "Bank Kalsel",
        "Bank Kalbar",
        "Bank Kaltimtara",
        "Bank Sulselbar",
        "Bank SulutGo",
        "Bank Sultra",
        "Bank NTB Syariah",
        "Bank NTT",
        "Bank Maluku Malut",
        "Bank Papua",
        "Bank BPD Bali",
        "Bank BPD DIY",
    ],
];
